@startuml
'https://plantuml.com/class-diagram

class main{
    string BUILDING_DIR_PATH
    string CALL_DIR_PATH
    string OUTPUT_PATH
    list combinations
    main()
    create_output()
    make_outputs()
}

class Elevator {
    + int max_floor
    + int min_floor
    + float speed
    float close_time
    float open_time
    float start_time
    float stop_time
    int direction
    int state
    list up_calls
    list down_calls
}


@enduml